Outputs:
  WebsiteURL:
    Description: "Website URL"
    Value: !Sub "https://${CloudFrontDistribution.DomainName}"

  BucketName:
    Description: "S3 Bucket Name"
    Value: !Ref WebsiteBucket

  PipelineName:
    Description: "CodePipeline Name"
    Value: !Ref CodePipeline

  CloudFrontDistributionId:
    Description: "CloudFront Distribution ID"
    Value: !Ref CloudFrontDistribution
